- hosts: localhost
  roles:
    - name: pddg.xkeysnail
      vars:
        # xkeysnail_config_dir: Use default (/etc/opt/xkeysnail)
        xkeysnail_config_file: "{{ lookup('env', 'PWD') }}/config.py"

